import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { ExternalLink, FileText, Plus, StickyNote } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { OwnerOnly } from "@/components/OwnerOnly";
import { Button } from "@/components/ui/button";
import { fetchShopContext, qk } from "@/lib/store";
import { peso } from "@/lib/format";

export const Route = createFileRoute("/_app/business")({ head: () => ({ meta: [{ title: "Business organizer — MVP BizManager" }, { name: "description", content: "Keep suppliers, expenses, notes and permits together." }, { property: "og:title", content: "Business organizer — MVP BizManager" }, { property: "og:description", content: "Keep suppliers, expenses, notes and permits together." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: BusinessPage });

function BusinessPage() {
  const { data: shop } = useQuery({ queryKey: qk.shop, queryFn: fetchShopContext });
  const { data: suppliers = [] } = useTable("suppliers");
  const { data: expenses = [] } = useTable("expenses");
  const { data: notes = [] } = useTable("shop_notes");
  const { data: documents = [] } = useTable("shop_documents");
  const month = new Date().toISOString().slice(0, 7);
  const monthly = expenses.filter((expense) => String(expense.date).startsWith(month)).reduce((sum, expense) => sum + Number(expense.amount), 0);
  const expiring = documents.filter((document) => document.expiry_date && new Date(document.expiry_date).getTime() - Date.now() <= 30 * 86400000 && new Date(document.expiry_date).getTime() >= Date.now());
  return <OwnerOnly><div className="space-y-6 p-4 md:p-8"><div><h1 className="text-3xl font-bold">Business organizer</h1><p className="text-muted-foreground">Suppliers, expenses, reminders and private files for {shop?.shop_name}.</p></div>{expiring.length > 0 && <div className="rounded-lg border border-warning bg-warning/10 p-4 text-sm"><b>⚠ Permit reminder:</b> {expiring.map((d) => `${d.title} expires ${new Date(String(d.expiry_date)).toLocaleDateString("en-PH")}`).join(", ")}</div>}<div className="grid gap-6 xl:grid-cols-2"><Suppliers rows={suppliers} shopId={shop?.shop_id}/><Expenses rows={expenses} shopId={shop?.shop_id} monthly={monthly}/><Notes rows={notes} shopId={shop?.shop_id}/><Documents rows={documents} shopId={shop?.shop_id}/></div></div></OwnerOnly>;
}

function useTable<T extends "suppliers" | "expenses" | "shop_notes" | "shop_documents">(table: T) { return useQuery({ queryKey: [table], queryFn: async () => { const { data, error } = await supabase.from(table).select("*").order("created_at", { ascending: false }); if (error) throw error; return data; } }); }
function Suppliers({ rows, shopId }: { rows: Array<{ id: string; name: string; contact_person: string | null; mobile: string | null }>; shopId?: string }) { const qc = useQueryClient(); const [name, setName] = useState(""); const add = async () => { if (!shopId || !name.trim()) return; const { error } = await supabase.from("suppliers").insert({ shop_id: shopId, name: name.trim() }); if (error) toast.error(error.message); else { setName(""); qc.invalidateQueries({ queryKey: ["suppliers"] }); } }; return <Panel title="Suppliers"><div className="flex gap-2"><input value={name} onChange={(e) => setName(e.target.value)} placeholder="Supplier name" className="min-w-0 flex-1 rounded-md border border-input bg-background px-3 py-2"/><Button size="icon" onClick={add} title="Add supplier"><Plus className="h-4 w-4"/></Button></div><ul className="mt-3 divide-y divide-border">{rows.map((row) => <li key={row.id} className="py-3"><b>{row.name}</b><p className="text-xs text-muted-foreground">{row.contact_person || "No contact person"}{row.mobile ? ` · ${row.mobile}` : ""}</p></li>)}</ul></Panel>; }
function Expenses({ rows, shopId, monthly }: { rows: Array<{ id: string; category: string; amount: number; date: string }>; shopId?: string; monthly: number }) { const qc = useQueryClient(); const [amount, setAmount] = useState(""); const [category, setCategory] = useState("supplies"); const add = async () => { const { data: user } = await supabase.auth.getUser(); if (!shopId || !user.user || Number(amount) <= 0) return; const { error } = await supabase.from("expenses").insert({ shop_id: shopId, amount: Number(amount), category: category as "supplies", created_by: user.user.id }); if (error) toast.error(error.message); else { setAmount(""); qc.invalidateQueries({ queryKey: ["expenses"] }); } }; return <Panel title={`Expenses · ${peso(monthly)} this month`}><div className="grid grid-cols-[1fr_1fr_auto] gap-2"><select value={category} onChange={(e) => setCategory(e.target.value)} className="rounded-md border border-input bg-background px-2 text-sm">{["rent","electricity","water","internet","salaries","supplies","transport","other"].map((v) => <option key={v}>{v}</option>)}</select><input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} placeholder="₱ Amount" className="min-w-0 rounded-md border border-input bg-background px-3 py-2"/><Button size="icon" onClick={add} title="Add expense"><Plus className="h-4 w-4"/></Button></div><ul className="mt-3 divide-y divide-border">{rows.slice(0, 8).map((row) => <li key={row.id} className="flex justify-between py-2 text-sm"><span className="capitalize">{row.category}<small className="ml-2 text-muted-foreground">{row.date}</small></span><b>{peso(Number(row.amount))}</b></li>)}</ul></Panel>; }
function Notes({ rows, shopId }: { rows: Array<{ id: string; note: string }>; shopId?: string }) { const qc = useQueryClient(); const [note, setNote] = useState(""); const add = async () => { const { data: user } = await supabase.auth.getUser(); if (!shopId || !user.user || !note.trim()) return; const { error } = await supabase.from("shop_notes").insert({ shop_id: shopId, note: note.trim(), created_by: user.user.id }); if (error) toast.error(error.message); else { setNote(""); qc.invalidateQueries({ queryKey: ["shop_notes"] }); } }; return <Panel title="Notes"><textarea maxLength={2000} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Supplier schedules or reminders" className="min-h-24 w-full rounded-md border border-input bg-background p-3"/><Button className="mt-2" onClick={add}><StickyNote className="h-4 w-4"/> Save note</Button><ul className="mt-3 space-y-2">{rows.map((row) => <li key={row.id} className="rounded-md bg-muted p-3 text-sm">{row.note}</li>)}</ul></Panel>; }
function Documents({ rows, shopId }: { rows: Array<{ id: string; title: string; type: string; expiry_date: string | null; file_path: string }>; shopId?: string }) { const qc = useQueryClient(); const [busy, setBusy] = useState(false); const upload = async (event: React.ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file || !shopId) return; if (!["application/pdf", "image/jpeg", "image/png"].includes(file.type) || file.size > 5 * 1024 * 1024) return toast.error("Choose a PDF, JPG or PNG under 5 MB"); setBusy(true); const path = `${shopId}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, "-")}`; const { error } = await supabase.storage.from("shop-documents").upload(path, file); if (error) { setBusy(false); return toast.error(error.message); } const { data: user } = await supabase.auth.getUser(); if (!user.user) return; const { error: rowError } = await supabase.from("shop_documents").insert({ shop_id: shopId, title: file.name, type: "other", file_path: path, mime_type: file.type, file_size: file.size, uploaded_by: user.user.id }); setBusy(false); if (rowError) toast.error(rowError.message); else qc.invalidateQueries({ queryKey: ["shop_documents"] }); }; const open = async (path: string) => { const { data, error } = await supabase.storage.from("shop-documents").createSignedUrl(path, 60); if (error) toast.error(error.message); else window.open(data.signedUrl, "_blank", "noopener,noreferrer"); }; return <Panel title="Private documents"><label className="inline-flex cursor-pointer items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground"><FileText className="h-4 w-4"/>{busy ? "Uploading…" : "Upload file"}<input type="file" accept="application/pdf,image/jpeg,image/png" className="sr-only" disabled={busy} onChange={upload}/></label><p className="mt-2 text-xs text-muted-foreground">PDF, JPG or PNG · maximum 5 MB · private signed links</p><ul className="mt-3 divide-y divide-border">{rows.map((row) => <li key={row.id} className="flex items-center justify-between py-3 text-sm"><span><b>{row.title}</b><small className="block text-muted-foreground capitalize">{row.type}{row.expiry_date ? ` · expires ${row.expiry_date}` : ""}</small></span><Button size="icon" variant="ghost" title="Open for 60 seconds" onClick={() => open(row.file_path)}><ExternalLink className="h-4 w-4"/></Button></li>)}</ul></Panel>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-lg border border-border bg-card p-5"><h2 className="mb-4 font-bold">{title}</h2>{children}</section>; }