import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Copy, Trash2, UserRound } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { OwnerOnly } from "@/components/OwnerOnly";
import { Button } from "@/components/ui/button";
import { peso } from "@/lib/format";

export const Route = createFileRoute("/_app/customers")({ head: () => ({ meta: [{ title: "Customers — MVP BizManager" }, { name: "description", content: "Understand repeat customers without sharing their details." }, { property: "og:title", content: "Customers — MVP BizManager" }, { property: "og:description", content: "Understand repeat customers without sharing their details." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: CustomersPage });

function CustomersPage() {
  const qc = useQueryClient();
  const { data = [] } = useQuery({ queryKey: ["customer-insights"], queryFn: async () => { const { data: customers, error } = await supabase.from("customers").select("*").is("anonymized_at", null).order("name"); if (error) throw error; const { data: sales, error: salesError } = await supabase.from("sales").select("customer_id,total,created_at,status").eq("status", "completed"); if (salesError) throw salesError; return customers.map((customer) => { const visits = sales.filter((sale) => sale.customer_id === customer.id); return { ...customer, visits: visits.length, spend: visits.reduce((sum, sale) => sum + Number(sale.total), 0), last: visits[0]?.created_at ?? null, visits30: visits.filter((sale) => Date.now() - new Date(sale.created_at).getTime() <= 30 * 86400000).length }; }); } });
  const [windowDays, setWindowDays] = useState<30 | 90>(30);
  const ranked = useMemo(() => [...data].filter((customer) => !customer.last || Date.now() - new Date(customer.last).getTime() <= windowDays * 86400000).sort((a, b) => b.spend - a.spend).slice(0, 10), [data, windowDays]);
  const inactive = data.filter((customer) => customer.last && Date.now() - new Date(customer.last).getTime() > 30 * 86400000);
  const anonymize = async (id: string) => { const { error } = await supabase.rpc("anonymize_customer", { _customer_id: id }); if (error) toast.error(error.message); else { toast.success("Customer details removed; past sales kept"); qc.invalidateQueries({ queryKey: ["customer-insights"] }); } };
  return <OwnerOnly><div className="space-y-6 p-4 md:p-8"><div><h1 className="flex items-center gap-2 text-3xl font-bold"><UserRound className="text-primary" /> Customers</h1><p className="text-muted-foreground">Know your regular customers. Their personal details never go to BIZBOT.</p></div><div className="grid gap-3 sm:grid-cols-3"><Stat label="Customers" value={data.length}/><Stat label="Repeat buyers (30 days)" value={data.filter((c) => c.visits30 >= 2).length}/><Stat label="Not back in 30 days" value={inactive.length}/></div><section className="rounded-lg border border-border bg-card p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-bold">Top customers</h2><div className="flex rounded-md bg-muted p-1">{([30, 90] as const).map((days) => <Button key={days} size="sm" variant={windowDays === days ? "default" : "ghost"} onClick={() => setWindowDays(days)}>{days} days</Button>)}</div></div><CustomerTable customers={ranked} onDelete={anonymize}/></section><section className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Hindi pa bumabalik in 30 days</h2><p className="text-sm text-muted-foreground">Copy a suggestion and send it yourself. The app never messages customers automatically.</p><div className="mt-4 space-y-3">{inactive.map((customer) => { const text = `Hi ${customer.name}! Miss ka na namin sa tindahan. May special offer kami para sa iyo this week.`; return <div key={customer.id} className="flex items-center justify-between gap-3 rounded-md border border-border p-3"><p className="text-sm">{text}</p><Button size="icon" variant="outline" title="Copy message" onClick={() => { navigator.clipboard.writeText(text); toast.success("Message copied"); }}><Copy className="h-4 w-4" /></Button></div>; })}{inactive.length === 0 && <p className="text-sm text-muted-foreground">No customers in this list.</p>}</div></section></div></OwnerOnly>;
}
function Stat({ label, value }: { label: string; value: number }) { return <div className="rounded-lg border border-border bg-card p-4"><p className="text-2xl font-bold">{value}</p><p className="text-sm text-muted-foreground">{label}</p></div>; }
function CustomerTable({ customers, onDelete }: { customers: Array<{ id: string; name: string; mobile: string | null; spend: number; visits: number; last: string | null }>; onDelete: (id: string) => void }) { return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="text-muted-foreground"><tr><th className="py-2">Name</th><th>Mobile</th><th>Spend</th><th>Visits</th><th>Last visit</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody className="divide-y divide-border">{customers.map((customer) => <tr key={customer.id}><td className="py-3 font-medium">{customer.name}</td><td>{customer.mobile || "—"}</td><td>{peso(customer.spend)}</td><td>{customer.visits}</td><td>{customer.last ? new Date(customer.last).toLocaleDateString("en-PH") : "—"}</td><td><Button size="icon" variant="ghost" title="Remove personal details" onClick={() => onDelete(customer.id)}><Trash2 className="h-4 w-4" /></Button></td></tr>)}</tbody></table></div>; }