import { createFileRoute, Link } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Area, AreaChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { AlertTriangle, ArrowRight, Bot, PackageX, ShoppingBag, TrendingUp, Wallet } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { computeInsights, fetchCashierToday, fetchDailyTip, fetchForecasts, fetchGoals, fetchItems, fetchProducts, fetchSales, fetchShopContext, loadSampleData, qk } from "@/lib/store";
import { peso, pesoShort } from "@/lib/format";
import { tooltipProps, axisProps, legendProps } from "@/lib/chart-theme";
import { useT } from "@/lib/i18n";
import { useCachedAt } from "@/lib/offline";
import { ActivityLogPanel, RefreshStatusPanel } from "@/components/OwnerPanels";

export const Route = createFileRoute("/_app/dashboard")({ head: () => ({ meta: [{ title: "Dashboard — MVP BizManager" }, { name: "description", content: "Sales, goals, forecasts and practical store insights." }, { property: "og:title", content: "Dashboard — MVP BizManager" }, { property: "og:description", content: "Sales, goals, forecasts and practical store insights." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: Dashboard });
const COLORS = ["var(--chart-1)", "var(--chart-2)", "var(--chart-3)", "var(--chart-4)", "var(--chart-5)"];

function Dashboard() {
  const { lang, t } = useT(); const cachedAt = useCachedAt(); const qc = useQueryClient(); const [forecastDays, setForecastDays] = useState<7 | 30>(7); const [seeding, setSeeding] = useState(false);
  const { data: shop, isError: shopError } = useQuery({ queryKey: qk.shop, queryFn: fetchShopContext, retry: 1 }); const owner = shop?.member_role === "owner";
  const products = useQuery({ queryKey: qk.products, queryFn: fetchProducts }); const sales = useQuery({ queryKey: qk.sales, queryFn: fetchSales, enabled: owner }); const items = useQuery({ queryKey: qk.items, queryFn: fetchItems, enabled: owner });
  const { data: goals = [] } = useQuery({ queryKey: qk.goals, queryFn: fetchGoals, enabled: owner }); const { data: forecasts = [] } = useQuery({ queryKey: qk.forecasts, queryFn: fetchForecasts, enabled: owner }); const { data: dailyTip } = useQuery({ queryKey: qk.tip, queryFn: fetchDailyTip });
  const { data: cashierToday } = useQuery({ queryKey: qk.cashierToday, queryFn: fetchCashierToday, enabled: shop?.member_role === "cashier" });
  const d = useMemo(() => {
    const S = (sales.data ?? []).filter((s) => s.status === "completed"), I = items.data ?? []; const now = Date.now(); const from = now - 7 * 86400000; const prevFrom = from - 7 * 86400000;
    const cur = S.filter((s) => new Date(s.created_at).getTime() >= from), prev = S.filter((s) => { const t = new Date(s.created_at).getTime(); return t >= prevFrom && t < from; });
    const rev = cur.reduce((a, s) => a + Number(s.total), 0), prevRev = prev.reduce((a, s) => a + Number(s.total), 0), cost = cur.reduce((a, s) => a + Number(s.cost_total), 0);
    const days = Array.from({ length: 7 }, (_, i) => { const day = new Date(now - (6 - i) * 86400000), prevDay = new Date(day.getTime() - 7 * 86400000); const sum = (date: Date) => S.filter((s) => new Date(s.created_at).toDateString() === date.toDateString()).reduce((a, s) => a + Number(s.total), 0); return { day: day.toLocaleDateString("en-PH", { weekday: "short" }), thisWeek: sum(day), lastWeek: sum(prevDay) }; });
    const curItems = I.filter((i) => new Date(i.created_at).getTime() >= from); const byCat = new Map<string, number>(); for (const i of curItems) byCat.set(i.category, (byCat.get(i.category) ?? 0) + Number(i.price) * i.qty);
    let cats = [...byCat.entries()].sort((a,b) => b[1]-a[1]).map(([name,sales]) => ({name,sales})); if (cats.length > 5) cats = [...cats.slice(0,5), { name: lang === "tl" ? "Iba pa" : "Others", sales: cats.slice(5).reduce((s,c)=>s+c.sales,0)}];
    const totalCat = cats.reduce((s,c)=>s+c.sales,0); const change = prevRev ? ((rev-prevRev)/prevRev)*100 : 0; return { rev, profit: rev-cost, orders: cur.length, days, cats: cats.map(c=>({...c, percent: totalCat ? Math.round(c.sales/totalCat*100):0})), change };
  }, [sales.data, items.data, lang]);
  const insights = useMemo(() => computeInsights(products.data ?? [], items.data ?? []), [products.data, items.data]); const overstock = insights.filter((i)=>i.kind==="overstock").length;
  const topCat = d.cats[0]?.name ?? (lang === "tl" ? "wala pa" : "none yet"); const changeText = `${d.change >= 0 ? "▲" : "▼"} ${lang === "tl" ? (d.change >= 0 ? "tumaas" : "bumaba") : (d.change >= 0 ? "up" : "down")} ${Math.abs(d.change).toFixed(0)}%`;
  const cards = [{label:lang==="tl"?"Benta ngayong linggo":"Sales this week",value:peso(d.rev),sub:`${d.change>=0?"▲":"▼"} ${Math.abs(d.change).toFixed(1)}% ${d.change>=0?(lang==="tl"?"mas mataas":"higher"):(lang==="tl"?"mas mababa":"lower")} than last week`,good:d.change>=0},{label:lang==="tl"?"Tubo":"Profit",value:peso(d.profit),sub:lang==="tl"?"pagkatapos ng puhunan":"after product cost",good:d.profit>=0},{label:lang==="tl"?"Tubo bawat ₱100 na benta":"Profit per ₱100 sold",value:peso(d.rev?d.profit/d.rev*100:0),sub:lang==="tl"?"sa bawat ₱100":"for every ₱100 sold",good:d.profit>=0},{label:lang==="tl"?"Bilang ng benta":"Number of sales",value:String(d.orders),sub:`${lang==="tl"?"Average na bili bawat customer":"Average per customer"}: ${peso(d.orders?d.rev/d.orders:0)}`,good:true}];
  const seed = async()=>{setSeeding(true);try{await loadSampleData();await qc.invalidateQueries();toast.success("Sample store loaded");}catch(e){toast.error(e instanceof Error?e.message:"Could not load sample data");}finally{setSeeding(false);}};
  const offlineNote = cachedAt ? <div role="status" className="flex items-center gap-2 rounded-lg border border-warning/50 bg-warning/10 p-3 text-sm"><b>{t("offline.dashTitle")}</b><span className="opacity-80">{t("offline.lastUpdated")}: {new Date(cachedAt).toLocaleString(lang==="tl"?"fil-PH":"en-PH",{dateStyle:"medium",timeStyle:"short"})}</span></div> : null;
  if(shopError||products.isError)return <div className="mx-auto max-w-md p-8 text-center"><h1 className="text-2xl font-bold">We couldn’t load your shop</h1><p className="mt-2 text-muted-foreground">{t("offline.noCache")}</p><button onClick={()=>window.location.reload()} className="mt-5 rounded-lg bg-primary px-4 py-2 font-semibold text-primary-foreground">Reload</button></div>;
  if(products.isLoading||!shop||(owner&&sales.isLoading))return <div className="p-8 text-muted-foreground">Loading…</div>;
  if(shop?.member_role === "cashier") return <div className="space-y-5 p-4 md:p-8">{offlineNote}<div><p className="text-sm text-muted-foreground">Cashier</p><h1 className="text-3xl font-bold">Today's sales</h1></div><div className="grid grid-cols-2 gap-3"><div className="rounded-lg border border-border bg-card p-5"><p className="text-3xl font-bold">{peso(Number(cashierToday?.today_total ?? 0))}</p><p className="text-sm text-muted-foreground">Total recorded today</p></div><div className="rounded-lg border border-border bg-card p-5"><p className="text-3xl font-bold">{String(cashierToday?.sale_count ?? 0)}</p><p className="text-sm text-muted-foreground">Number of sales</p></div></div><Link to="/pos" className="flex items-center justify-between rounded-lg bg-primary p-5 text-primary-foreground"><span><small className="block opacity-80">Record Cash, GCash or Card payments</small><b className="text-lg">New sale</b></span><ArrowRight/></Link></div>;
  if((products.data??[]).length===0)return <div className="mx-auto max-w-2xl p-6 md:p-12"><div className="rounded-lg border border-border bg-card p-8 text-center"><h1 className="text-3xl font-bold">Let's set up your store</h1><p className="mt-2 text-muted-foreground">Add your products, or load a sample store to explore.</p><button onClick={seed} disabled={seeding} className="mt-6 rounded-lg bg-primary px-5 py-2.5 font-semibold text-primary-foreground">{seeding?"Loading…":"Load sample store"}</button></div></div>;
  const shownForecast=forecasts.slice(0,forecastDays), low=shownForecast.reduce((s,f)=>s+Number(f.low),0), high=shownForecast.reduce((s,f)=>s+Number(f.high),0), busiest=[...shownForecast].sort((a,b)=>Number(b.expected_sales)-Number(a.expected_sales))[0];
   return <div className="space-y-5 p-4 md:p-8">{offlineNote}<div><p className="text-sm text-muted-foreground">{lang==="tl"?"Buod ng tindahan":"Store overview"}</p><h1 className="text-2xl font-bold md:text-3xl">{lang === "tl" ? <>Boss, {peso(d.rev)} ang benta mo ngayong linggo, <span className={d.change >= 0 ? "text-success" : "text-destructive"}>{changeText}</span>. Pinakamabenta ang {topCat}.</> : <>Boss, you sold {peso(d.rev)} this week, <span className={d.change >= 0 ? "text-success" : "text-destructive"}>{changeText}</span>. {topCat} sold the most.</>}</h1></div>
    {dailyTip && <div className="flex items-start justify-between gap-3 rounded-lg border border-warning/40 bg-warning/10 p-4"><div><p className="flex items-center gap-2 text-sm font-bold text-warning">⚠ <Bot className="h-4 w-4"/>Today's BIZBOT tip</p><p className="mt-1 text-sm">{dailyTip.tip_text}</p></div>{owner&&<div className="flex"><button aria-label="Helpful" onClick={()=>supabase.from("daily_tips").update({feedback:1}).eq("id",dailyTip.id)} className="p-2">👍</button><button aria-label="Not helpful" onClick={()=>supabase.from("daily_tips").update({feedback:-1}).eq("id",dailyTip.id)} className="p-2">👎</button></div>}</div>}
    <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{cards.map(c=><div key={c.label} className="rounded-lg border border-border bg-card p-4"><p className="text-2xl font-bold tabular-nums">{c.value}</p><p className="mt-1 text-sm text-muted-foreground">{c.label}</p><p className={`mt-2 text-xs font-semibold ${c.good?"text-success":"text-destructive"}`}>{c.sub}</p></div>)}</div>
    {goals.length>0&&<section className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold">Sales goals</h2><div className="mt-4 grid gap-4 md:grid-cols-3">{goals.map(g=>{const actual=g.period==="daily"?(sales.data??[]).filter(s=>s.status==="completed"&&new Date(s.created_at).toDateString()===new Date().toDateString()).reduce((x,s)=>x+Number(s.total),0):d.rev;const pct=Math.min(100,actual/Number(g.target_amount)*100);return <div key={g.id}><div className="flex justify-between text-sm capitalize"><b>{g.period}</b><span>{peso(actual)} of {peso(Number(g.target_amount))} ({Math.round(pct)}%)</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-muted"><div className={`h-full ${pct>=100?"bg-success":"bg-primary"}`} style={{width:`${pct}%`}}/></div><p className="mt-1 text-xs text-muted-foreground">{pct>=100?"Goal reached! 🎉":`${peso(Math.max(0,Number(g.target_amount)-actual))} to go`}</p></div>})}</div></section>}
    <div className="grid gap-4 xl:grid-cols-[1.6fr_1fr]"><section className="rounded-lg border border-border bg-card p-4"><h2 className="font-bold">{lang==="tl"?"Benta ngayong linggo":"Sales this week"}</h2><div className="h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={d.days}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" {...axisProps}/><YAxis {...axisProps} tickFormatter={pesoShort} width={48}/><Tooltip formatter={(v:number)=>peso(v)} {...tooltipProps}/><Legend {...legendProps}/><Line name={lang==="tl"?"Ngayong linggo":"This week"} dataKey="thisWeek" stroke="var(--chart-1)" strokeWidth={3}/><Line name="Last week" dataKey="lastWeek" stroke="var(--muted-foreground)" strokeDasharray="5 5"/></LineChart></ResponsiveContainer></div></section><section className="rounded-lg border border-border bg-card p-4"><h2 className="font-bold">{lang==="tl"?"Benta bawat kategorya":"Sales by category"}</h2><div className="h-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={d.cats} dataKey="sales" innerRadius={45} outerRadius={70} stroke="none">{d.cats.map((_,i)=><Cell key={i} fill={COLORS[i%5]}/>)}</Pie><Tooltip formatter={(v:number)=>peso(v)} {...tooltipProps}/></PieChart></ResponsiveContainer></div><ul className="space-y-1 text-sm text-foreground">{d.cats.map((c,i)=><li key={c.name} className="flex justify-between"><span><i className="mr-2 inline-block h-2 w-2 rounded-full" style={{background:COLORS[i%5]}}/>{c.name}</span><b>{c.percent}%</b></li>)}</ul></section></div>
    <section className="rounded-lg border border-border bg-card p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-bold">Forecast</h2><p className="text-xs text-muted-foreground">Updated today at 1:00 AM · Estimate based on your past sales. Actual sales may differ.</p></div><div className="flex rounded-md bg-muted p-1">{([7,30] as const).map(n=><button key={n} onClick={()=>setForecastDays(n)} className={`rounded px-3 py-1 text-sm ${forecastDays===n?"bg-primary text-primary-foreground":""}`}>{n} days</button>)}</div></div>{shownForecast.length===0?<p className="mt-5 rounded-md bg-muted p-4 text-sm">We need about 2 weeks of sales to forecast. Keep ringing up sales!</p>:<><p className="mt-5 text-2xl font-bold">{peso(low)} to {peso(high)}</p><p className="text-sm text-muted-foreground">Busiest expected day: {busiest?new Date(`${busiest.forecast_date}T00:00:00`).toLocaleDateString("en-PH",{weekday:"long",month:"short",day:"numeric"}):"—"}</p><div className="mt-3 h-52"><ResponsiveContainer width="100%" height="100%"><AreaChart data={shownForecast}><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis {...axisProps} dataKey="forecast_date" tickFormatter={(v:string)=>new Date(`${v}T00:00:00`).toLocaleDateString("en-PH",{month:"short",day:"numeric"})}/><YAxis {...axisProps} tickFormatter={pesoShort}/><Tooltip formatter={(v:number)=>peso(v)} {...tooltipProps}/><Area dataKey="high" stroke="transparent" fill="var(--chart-1)" fillOpacity={0.12}/><Area dataKey="low" stroke="transparent" fill="var(--card)"/><Area dataKey="expected_sales" stroke="var(--chart-1)" fill="transparent" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></>}</section>
    <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-lg border border-border bg-card p-5"><h2 className="font-bold text-warning">⚠ Stock warnings</h2><p className="mt-1 text-sm text-muted-foreground">{overstock} overstocked · {insights.filter(i=>i.kind==="dead").length} dead stock · <span className="text-destructive">▼ {insights.filter(i=>i.kind==="reorder").length} running low</span></p><ul className="mt-3 space-y-2">{insights.slice(0,5).map((i,k)=><li key={k} className="flex gap-2 rounded-md bg-muted p-3 text-sm">{i.kind==="reorder"?<AlertTriangle className="h-4 w-4 text-destructive"/>:<PackageX className="h-4 w-4 text-warning"/>}<span><b>{i.title}</b><small className="block text-muted-foreground">{i.detail}</small></span></li>)}</ul></section><Link to="/pos" className="flex items-center justify-between rounded-lg bg-primary p-5 text-primary-foreground"><span><small className="block opacity-80">Record Cash, GCash or Card payments</small><b className="text-lg">New sale</b></span><ArrowRight/></Link></div>
    <div className="grid gap-4 lg:grid-cols-[1.6fr_1fr]"><ActivityLogPanel lang={lang}/><RefreshStatusPanel lang={lang}/></div>
  </div>;
}
