-- Patch 4a-5: per-plan price wording (replaces the held Patch 3b Item 17). Server-only writes (Data Security N3).
INSERT INTO public.translations (key, lang, value, updated_at) VALUES
  ('price.per','en','/month',now()), ('price.per','tl','/buwan',now()),
  ('price.from','en','Plans from',now()), ('price.from','tl','Mga plano mula',now()),
  ('plan.price_note','en','One price per plan, not per shop. Every shop in your plan is included.',now()), ('plan.price_note','tl','Isang presyo kada plano, hindi kada shop. Kasama na ang lahat ng shop sa plano mo.',now()),
  ('plan.basic.name','en','Basic',now()), ('plan.basic.name','tl','Basic',now()),
  ('plan.standard.name','en','Standard',now()), ('plan.standard.name','tl','Standard',now()),
  ('plan.pro.name','en','Pro',now()), ('plan.pro.name','tl','Pro',now()),
  ('plan.basic.shops','en','1 shop',now()), ('plan.basic.shops','tl','1 shop',now()),
  ('plan.standard.shops','en','Up to 3 shops',now()), ('plan.standard.shops','tl','Hanggang 3 shop',now()),
  ('plan.pro.shops','en','Up to 5 shops',now()), ('plan.pro.shops','tl','Hanggang 5 shop',now()),
  ('plan.multishop_soon','en','Multi-shop coming soon',now()), ('plan.multishop_soon','tl','Malapit na ang multi-shop',now()),
  ('plan.basic.skus','en','500 products (SKUs) per shop',now()), ('plan.basic.skus','tl','500 produkto (SKU) kada shop',now()),
  ('plan.standard.skus','en','999 products (SKUs) per shop',now()), ('plan.standard.skus','tl','999 produkto (SKU) kada shop',now()),
  ('plan.pro.skus','en','Unlimited products',now()), ('plan.pro.skus','tl','Walang limit na produkto',now()),
  ('plan.basic.ads','en','Includes brand promotions',now()), ('plan.basic.ads','tl','May kasamang promo ng mga brand',now()),
  ('plan.noads','en','No ads',now()), ('plan.noads','tl','Walang ads',now()),
  ('plan.basic.menu','en','Printable menu, up to 12 pages',now()), ('plan.basic.menu','tl','Printable na menu, hanggang 12 pahina',now()),
  ('plan.standard.menu','en','AI Menu Builder, 24 animated pages',now()), ('plan.standard.menu','tl','AI Menu Builder, 24 animated na pahina',now()),
  ('plan.pro.menu','en','AI Menu Builder, unlimited pages',now()), ('plan.pro.menu','tl','AI Menu Builder, walang limit na pahina',now()),
  ('plan.smart_reorder','en','Best orders list (smart reorder)',now()), ('plan.smart_reorder','tl','Best orders list (smart reorder)',now()),
  ('plan.cashiers','en','Unlimited cashiers',now()), ('plan.cashiers','tl','Walang limit na cashier',now()),
  ('plan.offline','en','Works offline',now()), ('plan.offline','tl','Gumagana kahit offline',now()),
  ('plan.trial','en','14-day free trial of Standard, no card needed',now()), ('plan.trial','tl','14 araw na libreng trial ng Standard, walang card',now()),
  ('plan.trial_left','en','Standard trial: {n} days left',now()), ('plan.trial_left','tl','Standard trial: {n} araw na lang',now()),
  ('plan.choose','en','Choose plan',now()), ('plan.choose','tl','Piliin ang plano',now()),
  ('plan.change','en','Change plan',now()), ('plan.change','tl','Palitan ang plano',now()),
  ('plan.upgrade','en','Upgrade',now()), ('plan.upgrade','tl','Mag-upgrade',now()),
  ('plan.current','en','Your plan',now()), ('plan.current','tl','Ang plano mo',now()),
  ('plan.pending','en','Changes to {plan} on {date}',now()), ('plan.pending','tl','Magiging {plan} sa {date}',now()),
  ('plan.usage.products','en','{n} of {max} products',now()), ('plan.usage.products','tl','{n} sa {max} na produkto',now()),
  ('plan.near_limit','en','You''re close to your product limit.',now()), ('plan.near_limit','tl','Malapit ka na sa limit ng produkto.',now()),
  ('plan.locked.smart_reorder','en','Best orders list is on Standard and Pro.',now()), ('plan.locked.smart_reorder','tl','Nasa Standard at Pro ang Best orders list.',now())
ON CONFLICT (key, lang) DO UPDATE SET value = EXCLUDED.value, updated_at = now();
REVOKE INSERT, UPDATE, DELETE, TRUNCATE ON public.translations FROM anon, authenticated;