/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DeleteAccountRouteImport } from './routes/delete-account'
import { Route as InviteRouteImport } from './routes/invite'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppBusinessRouteImport } from './routes/_app/business'
import { Route as AppCopilotRouteImport } from './routes/_app/copilot'
import { Route as AppCustomersRouteImport } from './routes/_app/customers'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppInventoryRouteImport } from './routes/_app/inventory'
import { Route as AppPosRouteImport } from './routes/_app/pos'
import { Route as AppReordersRouteImport } from './routes/_app/reorders'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as ApiStoreImageRouteImport } from './routes/api/store-image'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase/index'
import { Route as ShowcaseBusinessRouteImport } from './routes/showcase/$business'
import { Route as ApiPublicBizbotRouteImport } from './routes/api/public/bizbot'
import { Route as ApiPublicDailyBusinessRefreshRouteImport } from './routes/api/public/daily-business-refresh'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DeleteAccountRoute = DeleteAccountRouteImport.update({
  id: '/delete-account',
  path: '/delete-account',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteRoute = InviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCopilotRoute = AppCopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReordersRoute = AppReordersRouteImport.update({
  id: '/reorders',
  path: '/reorders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiStoreImageRoute = ApiStoreImageRouteImport.update({
  id: '/api/store-image',
  path: '/api/store-image',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseBusinessRoute = ShowcaseBusinessRouteImport.update({
  id: '/showcase/$business',
  path: '/showcase/$business',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBizbotRoute = ApiPublicBizbotRouteImport.update({
  id: '/api/public/bizbot',
  path: '/api/public/bizbot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDailyBusinessRefreshRoute =
  ApiPublicDailyBusinessRefreshRouteImport.update({
    id: '/api/public/daily-business-refresh',
    path: '/api/public/daily-business-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe/webhook',
  path: '/api/public/stripe/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AppBillingRoute
  '/business': typeof AppBusinessRoute
  '/copilot': typeof AppCopilotRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/pos': typeof AppPosRoute
  '/reorders': typeof AppReordersRoute
  '/settings': typeof AppSettingsRoute
  '/api/store-image': typeof ApiStoreImageRoute
  '/showcase/$business': typeof ShowcaseBusinessRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/api/public/bizbot': typeof ApiPublicBizbotRoute
  '/api/public/daily-business-refresh': typeof ApiPublicDailyBusinessRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/billing': typeof AppBillingRoute
  '/business': typeof AppBusinessRoute
  '/copilot': typeof AppCopilotRoute
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventory': typeof AppInventoryRoute
  '/pos': typeof AppPosRoute
  '/reorders': typeof AppReordersRoute
  '/settings': typeof AppSettingsRoute
  '/api/store-image': typeof ApiStoreImageRoute
  '/showcase/$business': typeof ShowcaseBusinessRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/api/public/bizbot': typeof ApiPublicBizbotRoute
  '/api/public/daily-business-refresh': typeof ApiPublicDailyBusinessRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/delete-account': typeof DeleteAccountRoute
  '/invite': typeof InviteRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/business': typeof AppBusinessRoute
  '/_app/copilot': typeof AppCopilotRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventory': typeof AppInventoryRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/reorders': typeof AppReordersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/store-image': typeof ApiStoreImageRoute
  '/showcase/$business': typeof ShowcaseBusinessRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/api/public/bizbot': typeof ApiPublicBizbotRoute
  '/api/public/daily-business-refresh': typeof ApiPublicDailyBusinessRefreshRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/stripe/webhook': typeof ApiPublicStripeWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/delete-account'
    | '/invite'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/billing'
    | '/business'
    | '/copilot'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/pos'
    | '/reorders'
    | '/settings'
    | '/api/store-image'
    | '/showcase/$business'
    | '/showcase/'
    | '/api/public/bizbot'
    | '/api/public/daily-business-refresh'
    | '/api/public/payments/webhook'
    | '/api/public/stripe/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/delete-account'
    | '/invite'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/billing'
    | '/business'
    | '/copilot'
    | '/customers'
    | '/dashboard'
    | '/inventory'
    | '/pos'
    | '/reorders'
    | '/settings'
    | '/api/store-image'
    | '/showcase/$business'
    | '/showcase'
    | '/api/public/bizbot'
    | '/api/public/daily-business-refresh'
    | '/api/public/payments/webhook'
    | '/api/public/stripe/webhook'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/auth'
    | '/delete-account'
    | '/invite'
    | '/privacy'
    | '/refund-policy'
    | '/reset-password'
    | '/terms'
    | '/_app/billing'
    | '/_app/business'
    | '/_app/copilot'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/inventory'
    | '/_app/pos'
    | '/_app/reorders'
    | '/_app/settings'
    | '/api/store-image'
    | '/showcase/$business'
    | '/showcase/'
    | '/api/public/bizbot'
    | '/api/public/daily-business-refresh'
    | '/api/public/payments/webhook'
    | '/api/public/stripe/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DeleteAccountRoute: typeof DeleteAccountRoute
  InviteRoute: typeof InviteRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiStoreImageRoute: typeof ApiStoreImageRoute
  ShowcaseBusinessRoute: typeof ShowcaseBusinessRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  ApiPublicBizbotRoute: typeof ApiPublicBizbotRoute
  ApiPublicDailyBusinessRefreshRoute: typeof ApiPublicDailyBusinessRefreshRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delete-account': {
      id: '/delete-account'
      path: '/delete-account'
      fullPath: '/delete-account'
      preLoaderRoute: typeof DeleteAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite': {
      id: '/invite'
      path: '/invite'
      fullPath: '/invite'
      preLoaderRoute: typeof InviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/copilot': {
      id: '/_app/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof AppCopilotRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory': {
      id: '/_app/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reorders': {
      id: '/_app/reorders'
      path: '/reorders'
      fullPath: '/reorders'
      preLoaderRoute: typeof AppReordersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/store-image': {
      id: '/api/store-image'
      path: '/api/store-image'
      fullPath: '/api/store-image'
      preLoaderRoute: typeof ApiStoreImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/$business': {
      id: '/showcase/$business'
      path: '/showcase/$business'
      fullPath: '/showcase/$business'
      preLoaderRoute: typeof ShowcaseBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/bizbot': {
      id: '/api/public/bizbot'
      path: '/api/public/bizbot'
      fullPath: '/api/public/bizbot'
      preLoaderRoute: typeof ApiPublicBizbotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/daily-business-refresh': {
      id: '/api/public/daily-business-refresh'
      path: '/api/public/daily-business-refresh'
      fullPath: '/api/public/daily-business-refresh'
      preLoaderRoute: typeof ApiPublicDailyBusinessRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe/webhook': {
      id: '/api/public/stripe/webhook'
      path: '/api/public/stripe/webhook'
      fullPath: '/api/public/stripe/webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppCopilotRoute: typeof AppCopilotRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppPosRoute: typeof AppPosRoute
  AppReordersRoute: typeof AppReordersRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppCopilotRoute: AppCopilotRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppPosRoute: AppPosRoute,
  AppReordersRoute: AppReordersRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DeleteAccountRoute: DeleteAccountRoute,
  InviteRoute: InviteRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiStoreImageRoute: ApiStoreImageRoute,
  ShowcaseBusinessRoute: ShowcaseBusinessRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  ApiPublicBizbotRoute: ApiPublicBizbotRoute,
  ApiPublicDailyBusinessRefreshRoute: ApiPublicDailyBusinessRefreshRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
